### ISSUE TITLE
SVG import doesn't clean up polyline

### ISSUE THREAD

**Issue by iliis** [deepnest-io/Deepnest#120] opened 2023-08-27 01:33 UTC
Importing an SVG with paths described by the [polyline tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline) will result in open line segments instead of being merged into a closed path.

**To Reproduce**

1. Download the following file (right click and 'Save Image As...'). It contains three squares (from left to right):
    1. A rectangle [(svg:rect)](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect)
    2. A square made out of four paths [(svg:path)](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path)
    3. A square made out of four polylines [(svg:polyline)](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline).
    ![three_squares](https://github.com/deepnest-io/Deepnest/assets/933300/e1006e72-7150-4e65-9116-e6bcb3cea07e)
4. Import it in Deepnest

**Expected Behavior**
Three squares, as individual shapes.

**Observed Behavior**
Only the first two squares are correctly imported, the third one is ignored and shown in red.
![image](https://github.com/deepnest-io/Deepnest/assets/933300/e8042c35-7b0c-4104-bb13-51c9bca1d52d)

**Desktop:**
 - OS: Windows 10 Enterprise (10.0.19045 Build 19045)
 - Deepnest Version: [v1.1.4](https://github.com/deepnest-io/Deepnest/releases/tag/v1.1.4)

**Additional context**
This issue came up when trying to import an SVG exported by the SVG exporter from [OnShape](https://www.onshape.com/). Exporting DXF seems to run into the same problem.
I can work around the issue with Inkscape by selecting everything and applying 'Path' -> 'Object to Path'. However, on a production file this takes a really long time and isn't really practical.

**Comment by abebeos** [comment] 2023-08-27 08:32
Thank you for your thorough report. Development has just restarted after a long summer-break. We are currently stuck with funding (a major sponsor went silent), see https://github.com/deepnest-io/Deepnest/issues/109. After publishing version 1.1.5, work on detail level (like this issue) can happen.

**Comment by abebeos** [comment] 2023-08-27 08:37
@bosd can you please verify the bug and apply the https://github.com/deepnest-io/Deepnest/labels/confirmed label once done?

**Comment by abebeos** [comment] 2023-08-27 13:51
> Importing an SVG with paths described by the [polyline tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline) will

Are you sure that this is a commonly used construct? According to:

> Typically a polyline is used to create open shapes as the last point doesn't have to be connected to the first point. For closed shapes see thehttps://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon element.

"polygon" should be used.

### Issue

The issue seems to be:

=> Deepnest does not recognize shapes formed by multiple polylines

(which looks to me like a non-issue, or special-case/non-standard functionality)

**Comment by iliis** [comment] 2023-08-27 16:42
I do not know how common this is, but at least my CAD software exports a lot of shapes as polylines.
Here's an SVG straight from an OnShape drawing:

![onshape_raw](https://github.com/deepnest-io/Deepnest/assets/933300/14ff6611-6735-4d64-be8b-3f6e485e1cb1)

This actually loads fine, but has an unwanted border and thus loads as one single piece in Deepnest:

![image](https://github.com/deepnest-io/Deepnest/assets/933300/36168afd-ecaa-4e10-9c26-fbdbebc125b9)

When I ungroup the elements and remove the border in Inkscape and save it as (plain) SVG:
![onshape_without_groups_and_border_plain](https://github.com/deepnest-io/Deepnest/assets/933300/52ff294e-2dbf-416f-a8a2-568e2f71a658)

Then it looks like this in Deepnest:
![image](https://github.com/deepnest-io/Deepnest/assets/933300/945dc1b9-9e02-47bf-ad3b-64e04fe50e37)

Which is interesting, as some shapes are imported correctly, even though they are segmented polylines too. So maybe Deepnest tries to clean up the polylines but somehow fails for some? I tried various settings for the endpoint tolerance, but this didn't seem to have any effect.

---

I agree that maybe the CAD software should export with a different tag. However, this is a *2D drawing* I'm exporting (projected from the 3D geometry), which in general can contain open open shapes (e.g. arrows or dimensions), so maybe that's why they are exporting everything as polylines.

I would argue this is still an issue though, at least for myself and following Postel's law ("be conservative in what you do, be liberal in what you accept from others"). If I have time I'll have a look at the code, but I'm not used to JavaScript.

**Comment by abebeos** [comment] 2023-08-27 16:55
> my CAD software

Which is it? Maybe it has a configuration to tweak the output?

> Postel's law

No postel's law here. Just the brutal rality of "lack of sponsors"...

**Comment by iliis** [comment] 2023-08-27 17:28
> > my CAD software
> 
> Which is it? Maybe it has a configuration to tweak the output?

https://www.onshape.com/ and no, unfortunately it doesn't.

> No postel's law here. Just the brutal reality of "lack of sponsors"...

I can spare a couple bucks, but nothing major. But I'm also not expecting you to do anything, just thought I'd report my findings.

**Comment by abebeos** [comment] 2023-08-27 21:51
> I can spare a couple bucks, but nothing major.

A few "nothing major" (and some elasticity from my side) can do it.

I've invited you to a private repo with sponsor info.

> But I'm also not expecting you to do anything, just thought I'd report my findings.

I'll at minimum document the problem domain, thus it becomes easier to solve it (for me, later, or for others).



> I tried various settings for the endpoint tolerance, but this didn't seem to have any effect.

I had myself import failures with some test-data, after accidentally changing the deepnest configuration. So possilby play with other config options, too. Not only  endpoint tolerance

**Comment by abebeos** [comment] 2023-08-27 23:54
- off-topic-

> https://www.onshape.com/

is the free version workable?

**Comment by abebeos** [comment] 2023-08-29 11:57
> Which is interesting, as some shapes are imported correctly

it seems those imported contain all  circles (full/partial)

**Comment by abebeos** [comment] 2023-08-30 13:39
see https://github.com/deepnest-io/Deepnest/issues/124#issuecomment-1699113209

**Comment by abebeos** [comment] 2023-09-03 10:30
fixed in 1.1.9

**Comment by abebeos** [comment] 2023-09-05 23:27
@iliis OnShape export can now be directly imported (1.1.10)

**Comment by abebeos** [comment] 2023-09-08 10:15
@iliis , please see #130

**Comment by iliis** [comment] 2023-09-14 13:10
Thank you very much for woking on this! I've [replied at the other issue](https://github.com/deepnest-io/Deepnest/issues/130#issuecomment-1719422510).

**Comment by abebeos** [comment] 2023-09-26 16:46
@iliis , I'll reopen this as i'll publish 1.2.0 in the next days.

Funding deficit is anyways not your fault (you just came into the cross-fire).

**Comment by abebeos** [comment] 2023-09-30 18:53
@iliis , could you check this on your side to confirm it works?

**Closed** 2024-06-15 22:54 UTC
Labels: bug, confirmed
